#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          0
bspc config window_gap            20
#bspc config top_padding          15

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor \
        -n "$i" \
        -d $monitor/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
    let i++
done
NMON=$i
unset i

bspc rule -a LibTest state=floating
bspc rule -a qjackctl state=floating

feh --bs-scale ~/.dotfiles/wallpaper.jpg &
compton -c &
